# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: '' # expected as cmd line arg
  tag: '' # expected as cmd line arg
  pullPolicy: Always

port: 3000

dbInstance: packlist0:us-central1:packlist-dev

nameOverride: ''
fullnameOverride: ''

service: {}

ingress:
  hostName: '' # expected as cmd line arg
  tlsEnv: prod # prod or staging, use staging for testing

resources:
  limits:
    cpu: '2'
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

proxyResources:
  requests:
    cpu: 10m
    memory: 5Mi
  limits:
    cpu: 500m
    memory: 50Mi
