apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
{{ include "api.labels" . | indent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.port }}
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    app.kubernetes.io/name: {{ include "api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
